name: GitHub Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type - major, minor or patch"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: 'pnpm'
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Release Bot"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run bundle

      - name: Release
        run: npx release-it ${{github.event.inputs.releaseType}} --ci --no-git.requireCleanWorkingDir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}